apiVersion: apps/v1
kind: Deployment
metadata:
  name: AI-Plagiarsm-Detector
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: app
        image: app:latest
        ports:
          - name: http
            containerPort: 80