apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-plagiarsm-detector
  namespace: aiplagarismapp
  labels:
    app.kubernetes.io/name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: app
        image: app:latest
        ports:
          - name: http
            containerPort: 80
