
apiVersion: v1
kind: Service
metadata:
  name: ai-plagiarsm-detector
  namespace: aiplagarismapp
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: ai-plagiarsm-detector
    app.kubernetes.io/name: app
